
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Apr 23 2026 11:00:48 -03 (Apr 23 2026 14:00:48 UTC)

// Verification Directory fv/somador 

module somador(clk, rst_n, carry_i, a_i, b_i, carry_o, sum_o);
  input clk, rst_n, carry_i;
  input [7:0] a_i, b_i;
  output carry_o;
  output [7:0] sum_o;
  wire clk, rst_n, carry_i;
  wire [7:0] a_i, b_i;
  wire carry_o;
  wire [7:0] sum_o;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_67, n_68, n_70, n_71, n_72, n_74, n_76, n_78;
  wire n_80;
  DFFRHQX2 \sum_temp_reg[8] (.RN (rst_n), .CK (clk), .D (n_64), .Q
       (carry_o));
  DFFRHQX1 \sum_temp_reg[7] (.RN (rst_n), .CK (clk), .D (n_62), .Q
       (sum_o[7]));
  DFFRHQX2 \sum_temp_reg[6] (.RN (rst_n), .CK (clk), .D (n_63), .Q
       (sum_o[6]));
  DFFRHQX2 \sum_temp_reg[5] (.RN (rst_n), .CK (clk), .D (n_59), .Q
       (sum_o[5]));
  DFFRHQX2 \sum_temp_reg[3] (.RN (rst_n), .CK (clk), .D (n_60), .Q
       (sum_o[3]));
  OAI21X2 g8517__2398(.A0 (n_13), .A1 (n_61), .B0 (n_12), .Y (n_64));
  CLKXOR2X1 g8515__5107(.A (n_31), .B (n_58), .Y (n_63));
  CLKXOR2X1 g8518__6260(.A (n_14), .B (n_61), .Y (n_62));
  DFFRHQX2 \sum_temp_reg[4] (.RN (rst_n), .CK (clk), .D (n_57), .Q
       (sum_o[4]));
  CLKXOR2X1 g8516__4319(.A (n_15), .B (n_55), .Y (n_60));
  CLKXOR2X1 g8514__8428(.A (n_32), .B (n_52), .Y (n_59));
  DFFRHQX2 \sum_temp_reg[2] (.RN (rst_n), .CK (clk), .D (n_54), .Q
       (sum_o[2]));
  AOI21X4 g8522__5526(.A0 (n_38), .A1 (n_56), .B0 (n_37), .Y (n_58));
  CLKXOR2X1 g8525__6783(.A (n_56), .B (n_11), .Y (n_57));
  AOI21X4 g8526__3680(.A0 (n_39), .A1 (n_56), .B0 (n_46), .Y (n_61));
  OAI21X2 g8523__1617(.A0 (n_67), .A1 (n_53), .B0 (n_17), .Y (n_55));
  CLKXOR2X1 g8524__2802(.A (n_18), .B (n_53), .Y (n_54));
  OAI21X4 g8521__1705(.A0 (n_50), .A1 (n_41), .B0 (n_35), .Y (n_52));
  DFFRHQX2 \sum_temp_reg[1] (.RN (rst_n), .CK (clk), .D (n_51), .Q
       (sum_o[1]));
  NAND2X8 g8531__5122(.A (n_43), .B (n_48), .Y (n_56));
  DFFRHQX4 \sum_temp_reg[0] (.RN (rst_n), .CK (clk), .D (n_45), .Q
       (sum_o[0]));
  NOR2X6 g8529__8246(.A (n_71), .B (n_49), .Y (n_53));
  CLKXOR2X1 g8530__7098(.A (n_47), .B (n_24), .Y (n_51));
  NOR2X4 g8528__6131(.A (n_74), .B (n_49), .Y (n_50));
  NAND2X8 g8533__1881(.A (n_47), .B (n_27), .Y (n_48));
  NOR2X4 g8534__5115(.A (n_26), .B (n_44), .Y (n_49));
  OAI21X4 g8536__7482(.A0 (n_2), .A1 (n_36), .B0 (n_30), .Y (n_46));
  XNOR2X1 g8538__4733(.A (carry_i), .B (n_28), .Y (n_45));
  CLKINVX6 g8535(.A (n_44), .Y (n_47));
  AOI21X4 g8537__6161(.A0 (n_40), .A1 (n_42), .B0 (n_34), .Y (n_43));
  NAND2X4 g8539__9315(.A (n_33), .B (n_80), .Y (n_41));
  INVX2 g8542(.A (n_36), .Y (n_37));
  AOI21X2 g8543__9945(.A0 (n_33), .A1 (n_76), .B0 (n_22), .Y (n_35));
  NOR2X8 g8545__2883(.A (n_5), .B (n_19), .Y (n_44));
  NOR2BX1 g8549__2346(.AN (n_20), .B (n_21), .Y (n_32));
  NAND2X1 g8551__1666(.A (n_30), .B (n_29), .Y (n_31));
  NOR2X4 g8557__7410(.A (n_6), .B (n_9), .Y (n_28));
  NOR3X6 g8541__6417(.A (n_16), .B (n_25), .C (n_26), .Y (n_27));
  NOR2X4 g8548__5477(.A (n_26), .B (n_70), .Y (n_24));
  OAI21X4 g8544__2398(.A0 (n_22), .A1 (n_21), .B0 (n_20), .Y (n_36));
  NOR2X8 g8552__5107(.A (n_8), .B (n_1), .Y (n_19));
  NAND2BX2 g8553__6260(.AN (n_68), .B (n_17), .Y (n_18));
  NAND2X6 g8547__4319(.A (n_7), .B (n_17), .Y (n_42));
  NOR2X8 g8550__8428(.A (n_16), .B (n_25), .Y (n_40));
  NOR2X1 g8555__5526(.A (n_78), .B (n_76), .Y (n_15));
  NAND2BX1 g8554__6783(.AN (n_13), .B (n_12), .Y (n_14));
  NOR2X1 g8546__3680(.A (n_10), .B (n_22), .Y (n_11));
  NOR2X6 g8556__1617(.A (n_10), .B (n_3), .Y (n_38));
  NOR2X4 g8560__2802(.A (a_i[0]), .B (n_8), .Y (n_9));
  INVX2 g8558(.A (n_10), .Y (n_33));
  NOR2X4 g8559__1705(.A (b_i[0]), .B (n_4), .Y (n_6));
  NOR2X6 g8572__5122(.A (n_4), .B (n_0), .Y (n_5));
  INVX2 g8568(.A (n_3), .Y (n_20));
  INVX2 g8570(.A (n_2), .Y (n_29));
  NOR2X8 g8571__8246(.A (a_i[0]), .B (carry_i), .Y (n_1));
  NOR2X4 g8579__7098(.A (b_i[6]), .B (a_i[6]), .Y (n_2));
  CLKAND2X3 g8573__6131(.A (b_i[5]), .B (a_i[5]), .Y (n_21));
  NOR2X2 g8562__1881(.A (b_i[7]), .B (a_i[7]), .Y (n_13));
  NAND2X2 g8563__5115(.A (b_i[6]), .B (a_i[6]), .Y (n_30));
  NAND2X2 g8561__7482(.A (b_i[7]), .B (a_i[7]), .Y (n_12));
  NAND2X8 g8575__4733(.A (b_i[2]), .B (a_i[2]), .Y (n_17));
  NOR2X6 g8574__6161(.A (b_i[5]), .B (a_i[5]), .Y (n_3));
  NAND2X8 g8576__9315(.A (b_i[1]), .B (a_i[1]), .Y (n_7));
  AND2X6 g8577__9945(.A (b_i[3]), .B (a_i[3]), .Y (n_34));
  NOR2X8 g8566__2883(.A (b_i[4]), .B (a_i[4]), .Y (n_10));
  NOR2X6 g8564__2346(.A (b_i[1]), .B (a_i[1]), .Y (n_26));
  NOR2X8 g8578__1666(.A (b_i[3]), .B (a_i[3]), .Y (n_16));
  CLKAND2X3 g8565__7410(.A (b_i[4]), .B (a_i[4]), .Y (n_22));
  NOR2X8 g8567__6417(.A (b_i[2]), .B (a_i[2]), .Y (n_25));
  CLKINVX20 g8581(.A (a_i[0]), .Y (n_4));
  CLKINVX6 g8582(.A (carry_i), .Y (n_0));
  CLKINVX20 g8580(.A (b_i[0]), .Y (n_8));
  BUFX6 fopt(.A (n_68), .Y (n_67));
  BUFX6 fopt1(.A (n_25), .Y (n_68));
  CLKINVX4 fopt8594(.A (n_72), .Y (n_70));
  INVX4 fopt8595(.A (n_72), .Y (n_71));
  BUFX6 fopt2(.A (n_7), .Y (n_72));
  BUFX6 fopt8596(.A (n_42), .Y (n_74));
  BUFX6 fopt8597(.A (n_34), .Y (n_76));
  BUFX3 fopt8598(.A (n_16), .Y (n_78));
  BUFX3 fopt8599(.A (n_40), .Y (n_80));
  CLKAND2X2 g8601__5477(.A (n_38), .B (n_29), .Y (n_39));
endmodule

