/*
###############################################################
#  Generated by:      Cadence Innovus 25.13-s088_1
#  OS:                Linux x86_64(Host ID ecomp)
#  Generated on:      Mon May  4 12:49:30 2026
#  Design:            somador
#  Command:           write_netlist /home/ufsm00291/ufsm00291-lima202020189/projetos/somador/backend/layout/deliverables/somador_worst_100_500/somador_layout.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Apr 23 2026 10:52:09 -03 (Apr 23 2026 13:52:09 UTC)
// Verification Directory fv/somador 
module somador (
	clk, 
	rst_n, 
	carry_i, 
	a_i, 
	b_i, 
	carry_o, 
	sum_o);
   input clk;
   input rst_n;
   input carry_i;
   input [7:0] a_i;
   input [7:0] b_i;
   output carry_o;
   output [7:0] sum_o;

   // Internal wires
   wire CTS_1;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;

   CLKBUFX2 CTS_cdb_buf_00009 (.Y(CTS_1),
	.A(clk));
   DFFRHQX8 \sum_temp_reg[8]  (.Q(carry_o),
	.D(n_14),
	.RN(rst_n),
	.CK(CTS_1));
   DFFRHQX8 \sum_temp_reg[7]  (.Q(sum_o[7]),
	.D(n_15),
	.RN(rst_n),
	.CK(CTS_1));
   ADDFX1 g592__2398 (.CO(n_14),
	.S(n_15),
	.A(a_i[7]),
	.B(b_i[7]),
	.CI(n_12));
   DFFRHQX8 \sum_temp_reg[6]  (.Q(sum_o[6]),
	.D(n_13),
	.RN(rst_n),
	.CK(CTS_1));
   ADDFX1 g594__5107 (.CO(n_12),
	.S(n_13),
	.A(a_i[6]),
	.B(b_i[6]),
	.CI(n_10));
   DFFRHQX8 \sum_temp_reg[5]  (.Q(sum_o[5]),
	.D(n_11),
	.RN(rst_n),
	.CK(CTS_1));
   ADDFX1 g596__6260 (.CO(n_10),
	.S(n_11),
	.A(a_i[5]),
	.B(b_i[5]),
	.CI(n_8));
   DFFRHQX8 \sum_temp_reg[4]  (.Q(sum_o[4]),
	.D(n_9),
	.RN(rst_n),
	.CK(CTS_1));
   ADDFX1 g598__4319 (.CO(n_8),
	.S(n_9),
	.A(a_i[4]),
	.B(b_i[4]),
	.CI(n_6));
   DFFRHQX8 \sum_temp_reg[3]  (.Q(sum_o[3]),
	.D(n_7),
	.RN(rst_n),
	.CK(CTS_1));
   ADDFX1 g600__8428 (.CO(n_6),
	.S(n_7),
	.A(a_i[3]),
	.B(b_i[3]),
	.CI(n_4));
   DFFRHQX8 \sum_temp_reg[2]  (.Q(sum_o[2]),
	.D(n_5),
	.RN(rst_n),
	.CK(CTS_1));
   ADDFX1 g602__5526 (.CO(n_4),
	.S(n_5),
	.A(a_i[2]),
	.B(b_i[2]),
	.CI(n_2));
   DFFRHQX8 \sum_temp_reg[1]  (.Q(sum_o[1]),
	.D(n_3),
	.RN(rst_n),
	.CK(CTS_1));
   ADDFX1 g604__6783 (.CO(n_2),
	.S(n_3),
	.A(a_i[1]),
	.B(b_i[1]),
	.CI(n_0));
   DFFRHQX8 \sum_temp_reg[0]  (.Q(sum_o[0]),
	.D(n_1),
	.RN(rst_n),
	.CK(CTS_1));
   ADDFX1 g606__3680 (.CO(n_0),
	.S(n_1),
	.A(carry_i),
	.B(a_i[0]),
	.CI(b_i[0]));
endmodule

