
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Apr 16 2026 07:02:54 -03 (Apr 16 2026 10:02:54 UTC)

// Verification Directory fv/somador 

module somador(clk, rst_n, carry_i, a_i, b_i, carry_o, sum_o);
  input clk, rst_n, carry_i;
  input [7:0] a_i, b_i;
  output carry_o;
  output [7:0] sum_o;
  wire clk, rst_n, carry_i;
  wire [7:0] a_i, b_i;
  wire carry_o;
  wire [7:0] sum_o;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32;
  DFFRHQX1 \sum_temp_reg[8] (.RN (rst_n), .CK (clk), .D (n_31), .Q
       (carry_o));
  DFFRHQX1 \sum_temp_reg[7] (.RN (rst_n), .CK (clk), .D (n_32), .Q
       (sum_o[7]));
  ADDFX1 g661__2398(.A (n_6), .B (n_15), .CI (n_29), .CO (n_31), .S
       (n_32));
  DFFRHQX1 \sum_temp_reg[6] (.RN (rst_n), .CK (clk), .D (n_30), .Q
       (sum_o[6]));
  ADDFX1 g663__5107(.A (n_4), .B (n_7), .CI (n_27), .CO (n_29), .S
       (n_30));
  DFFRHQX1 \sum_temp_reg[5] (.RN (rst_n), .CK (clk), .D (n_28), .Q
       (sum_o[5]));
  ADDFX1 g665__6260(.A (n_8), .B (n_1), .CI (n_25), .CO (n_27), .S
       (n_28));
  DFFRHQX1 \sum_temp_reg[4] (.RN (rst_n), .CK (clk), .D (n_26), .Q
       (sum_o[4]));
  ADDFX1 g667__4319(.A (n_5), .B (n_10), .CI (n_23), .CO (n_25), .S
       (n_26));
  DFFRHQX1 \sum_temp_reg[3] (.RN (rst_n), .CK (clk), .D (n_24), .Q
       (sum_o[3]));
  ADDFX1 g669__8428(.A (n_9), .B (n_13), .CI (n_21), .CO (n_23), .S
       (n_24));
  DFFRHQX1 \sum_temp_reg[2] (.RN (rst_n), .CK (clk), .D (n_22), .Q
       (sum_o[2]));
  ADDFX1 g671__5526(.A (n_16), .B (n_0), .CI (n_19), .CO (n_21), .S
       (n_22));
  DFFRHQX1 \sum_temp_reg[1] (.RN (rst_n), .CK (clk), .D (n_20), .Q
       (sum_o[1]));
  ADDFX1 g673__6783(.A (n_3), .B (n_12), .CI (n_17), .CO (n_19), .S
       (n_20));
  DFFRHQX1 \sum_temp_reg[0] (.RN (rst_n), .CK (clk), .D (n_18), .Q
       (sum_o[0]));
  ADDFX1 g675__3680(.A (n_2), .B (n_11), .CI (n_14), .CO (n_17), .S
       (n_18));
  BUFX2 g680(.A (a_i[2]), .Y (n_16));
  BUFX2 g684(.A (b_i[7]), .Y (n_15));
  BUFX2 g683(.A (carry_i), .Y (n_14));
  BUFX2 g682(.A (b_i[3]), .Y (n_13));
  BUFX2 g685(.A (b_i[1]), .Y (n_12));
  BUFX2 g691(.A (b_i[0]), .Y (n_11));
  BUFX2 g677(.A (b_i[4]), .Y (n_10));
  BUFX2 g689(.A (a_i[3]), .Y (n_9));
  BUFX2 g678(.A (a_i[5]), .Y (n_8));
  BUFX2 g687(.A (b_i[6]), .Y (n_7));
  BUFX2 g688(.A (a_i[7]), .Y (n_6));
  BUFX2 g679(.A (a_i[4]), .Y (n_5));
  BUFX2 g681(.A (a_i[6]), .Y (n_4));
  BUFX2 g676(.A (a_i[1]), .Y (n_3));
  BUFX2 g692(.A (a_i[0]), .Y (n_2));
  BUFX2 g686(.A (b_i[5]), .Y (n_1));
  BUFX2 g690(.A (b_i[2]), .Y (n_0));
endmodule

