
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Apr 16 2026 10:35:03 -03 (Apr 16 2026 13:35:03 UTC)

// Verification Directory fv/somador 

module somador(clk, rst_n, carry_i, a_i, b_i, carry_o, sum_o);
  input clk, rst_n, carry_i;
  input [7:0] a_i, b_i;
  output carry_o;
  output [7:0] sum_o;
  wire clk, rst_n, carry_i;
  wire [7:0] a_i, b_i;
  wire carry_o;
  wire [7:0] sum_o;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  DFFRHQX8 \sum_temp_reg[8] (.RN (rst_n), .CK (clk), .D (n_38), .Q
       (carry_o));
  DFFRHQX8 \sum_temp_reg[7] (.RN (rst_n), .CK (clk), .D (n_37), .Q
       (sum_o[7]));
  OAI2BB1X1 g791__2398(.A0N (n_12), .A1N (n_36), .B0 (n_13), .Y (n_38));
  XNOR2X1 g792__5107(.A (n_14), .B (n_36), .Y (n_37));
  DFFRHQX8 \sum_temp_reg[6] (.RN (rst_n), .CK (clk), .D (n_35), .Q
       (sum_o[6]));
  ADDFHX2 g794__6260(.A (b_i[6]), .B (a_i[6]), .CI (n_33), .CO (n_36),
       .S (n_35));
  DFFRHQX8 \sum_temp_reg[5] (.RN (rst_n), .CK (clk), .D (n_34), .Q
       (sum_o[5]));
  XNOR2X1 g797__4319(.A (n_20), .B (n_32), .Y (n_34));
  OAI21X4 g796__8428(.A0 (n_18), .A1 (n_32), .B0 (n_19), .Y (n_33));
  DFFRHQX8 \sum_temp_reg[4] (.RN (rst_n), .CK (clk), .D (n_31), .Q
       (sum_o[4]));
  AOI21X4 g799__5526(.A0 (n_1), .A1 (n_30), .B0 (n_21), .Y (n_32));
  CLKXOR2X1 g800__6783(.A (n_22), .B (n_30), .Y (n_31));
  DFFRHQX8 \sum_temp_reg[3] (.RN (rst_n), .CK (clk), .D (n_29), .Q
       (sum_o[3]));
  OAI21X4 g802__3680(.A0 (n_5), .A1 (n_28), .B0 (n_6), .Y (n_30));
  XNOR2X1 g803__1617(.A (n_7), .B (n_28), .Y (n_29));
  DFFRHQX8 \sum_temp_reg[2] (.RN (rst_n), .CK (clk), .D (n_27), .Q
       (sum_o[2]));
  XNOR2X1 g806__2802(.A (n_26), .B (n_10), .Y (n_27));
  AOI21X4 g805__1705(.A0 (n_8), .A1 (n_26), .B0 (n_9), .Y (n_28));
  DFFRHQX8 \sum_temp_reg[1] (.RN (rst_n), .CK (clk), .D (n_25), .Q
       (sum_o[1]));
  OAI21X4 g808__5122(.A0 (n_15), .A1 (n_24), .B0 (n_16), .Y (n_26));
  XNOR2X1 g809__8246(.A (n_24), .B (n_17), .Y (n_25));
  DFFRHQX8 \sum_temp_reg[0] (.RN (rst_n), .CK (clk), .D (n_23), .Q
       (sum_o[0]));
  XNOR2X1 g811__7098(.A (carry_i), .B (n_4), .Y (n_23));
  NOR2X6 g813__6131(.A (n_2), .B (n_11), .Y (n_24));
  ADDHX1 g812__1881(.A (b_i[4]), .B (a_i[4]), .CO (n_21), .S (n_22));
  NOR2BX1 g814__5115(.AN (n_19), .B (n_18), .Y (n_20));
  NOR2BX1 g815__7482(.AN (n_16), .B (n_15), .Y (n_17));
  NAND2X1 g816__4733(.A (n_13), .B (n_12), .Y (n_14));
  NOR2X4 g817__6161(.A (n_0), .B (n_3), .Y (n_11));
  NAND2BX1 g818__9315(.AN (n_9), .B (n_8), .Y (n_10));
  NOR2BX1 g820__9945(.AN (n_6), .B (n_5), .Y (n_7));
  XNOR2X1 g819__2883(.A (b_i[0]), .B (a_i[0]), .Y (n_4));
  NAND2X2 g824__2346(.A (b_i[7]), .B (a_i[7]), .Y (n_13));
  NAND2X2 g825__1666(.A (b_i[1]), .B (a_i[1]), .Y (n_16));
  NAND2X2 g826__7410(.A (b_i[5]), .B (a_i[5]), .Y (n_19));
  NOR2X2 g827__6417(.A (b_i[3]), .B (a_i[3]), .Y (n_5));
  OR2X1 g828__5477(.A (b_i[7]), .B (a_i[7]), .Y (n_12));
  AND2X1 g829__2398(.A (b_i[2]), .B (a_i[2]), .Y (n_9));
  NOR2X6 g823__5107(.A (a_i[0]), .B (carry_i), .Y (n_3));
  AND2X4 g821__6260(.A (a_i[0]), .B (carry_i), .Y (n_2));
  OR2X1 g822__4319(.A (b_i[4]), .B (a_i[4]), .Y (n_1));
  NOR2X2 g833__8428(.A (b_i[1]), .B (a_i[1]), .Y (n_15));
  NOR2X2 g831__5526(.A (b_i[5]), .B (a_i[5]), .Y (n_18));
  NAND2X2 g832__6783(.A (b_i[3]), .B (a_i[3]), .Y (n_6));
  OR2X1 g830__3680(.A (b_i[2]), .B (a_i[2]), .Y (n_8));
  INVX2 g834(.A (b_i[0]), .Y (n_0));
endmodule

